local M = {}
-- Ryu quotes from:
--   https://streetfighter.fandom.com/wiki/Ryu/Quotes
local quotes = {
  "Hadoken!",
  "Shoryuken!",
  "Tatsumaki Senpukyaku!",
  "To live is to fight, to fight is to live!",
  "There's nothing like a fair fight. It improves both competitors.",
  "You must love competition before you can achieve victory.",
  "Don't fight for victory--fight to improve yourself. Victory will come.",
  "This was a battle of spirits, not fists. Search your soul if you want to beat me!",
  "I really broke a sweat! How about another round?",
  "Blind pride can only hold you back. There are fighters out there stronger than either of us!",
  "If you want to be a true fighter... go and train!",
  "I know you can do better! Get up and try again!",
  "I see a strong will to fight in your eyes! Don't give up yet!",
  "One fight. One more step on the path to becoming a true warrior!",
  "Sometimes the most important battle, is the battle within...",
  "The only way a true fighter can suffer, is by not fighting!",
  "True victory is to give all of yourself, without regret.",
  "Whatever you find worthwhile in life, is worth fighting for!",
  "Whether we win or lose, all of our battles make us stronger!",
  "Your strength is equal to that of your will to win!",
  "Get up! Show me your true power!",
  "You're wounded. The hot springs can heal you quickly.",
  "You still have a fighting spirit in your eyes. I look forward to our next battle.",
  "These two fists are everything to me!",
  "Put everything you've got in your fist and challenge me!",
  "The world is big! There must be no limit to human strength...",
  "We are different, but I respect your fighting spirit. I'd like to challenge you again!",
  "Your power is splendid! If you sharpen your moves and toughen your mind, you'll be complete!",
  "If defeat discourages your fighting spirit, think of what you have gained by learning.",
  "You possess great ability at your age! I have rarely seen such potential. Only once before...",
  "The eyes of a warrior never stray from the spectacle of battle.",
  "To try something new, is to explore your true potential.",
  "Keep your mind calm and pure. Focus on what is important!",
  "It's better to conquer a hardship than to conquer nothing at all.",
  "A defeat learned from is more important than an empty victory.",
  "Range... Speed... Priority... Know and master all of your attacks!",
  "Every moment gives us a chance to become more than what we are.",
  "Seek an opponent who is your equal. Only then can you improve.",
  "You are already giving up? You didn't even try...",
  "That's it? Has your fighting spirit burned out?!",
  "I noticed the spirit of a true warrior was within you.",
  "A true warrior follows their own destiny!",
  "What strength! I won't forget that there are many like you all over the world!",
  "You were your own worst enemy...",
  "Never give into your fear...",
  "That look in your eyes... Never forget the fighting spirit you feel now.",
  "I'm ready for a rematch should we cross paths again.",
  "I've a better understanding now of what it means to be a true warrior...",
  "A clenched fist speaks louder than a hundred words.",
  "What a fight! You have my gratitude.",
  "You must defeat my Shoryuken to stand a chance!",
  "I walk my own path, regardless of what direction other men take.",
  "This is the power of Hado! The spirit channeled through the fist!",
  "Don´t forget the training you´ve had until now! Get up and fight again!",
  "My journey to become the ultimate fighter has only just begun.",
  "Each time I fight, I learn something new. This journey has been fruitful.",
  "Even if my fists were to turn to dust, I would not give up in my quest!",
  "The more I learn, the more I realize how far I am from the end of my journey.",
  "The power I am after is the power to win - not the power to destroy!",
  "If you go into the ring expecting to fail, you will. Believe in yourself!",
  "Give it your all!",
  "As long as I'm standing, I can still fight!",
  "I still have a long journey before I am a true warrior...",
  "It was my pleasure to meet a warrior who fights with honor. I hope that our paths will cross again.",
  "I see you are battling your inner demons. You must prove that you are stronger than they are.",
}

M.getQuote = function()
  local quote = quotes[math.random(#quotes)]
  return quote
end

return M
